# Generated by Django 4.1 on 2022-09-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Report_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Report_title', models.CharField(max_length=200)),
                ('File_Type', models.CharField(max_length=200)),
                ('Date_Created', models.DateField(verbose_name='Date report created')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.user')),
            ],
        ),
    ]
