# Generated by Django 4.1 on 2022-10-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(default='/media/test.txt', upload_to=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='Report_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
