# Generated by Django 4.1 on 2022-10-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_file_alter_report_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Owner',
        ),
    ]
