# Generated by Django 4.1 on 2022-10-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='file',
            new_name='File',
        ),
        migrations.RemoveField(
            model_name='report',
            name='File_Type',
        ),
        migrations.AddField(
            model_name='report',
            name='Report_Type',
            field=models.CharField(choices=[('Task Report', 'Task Report'), ('Product Report', 'Product Report'), ('Employee Report', 'Employee Report'), ('Financial Report', 'Financial Report')], default='Task Report', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='Date_Created',
            field=models.DateField(default='2022-10-12', verbose_name='Date report created'),
        ),
    ]
