# Generated by Django 4.1 on 2022-10-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_file_report_file_remove_report_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='File',
            field=models.FileField(default='test.txt', upload_to=None),
        ),
    ]
