# Generated by Django 4.1 on 2022-09-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('Date', models.DateField(verbose_name='Date incurred')),
                ('Amount', models.IntegerField(default=0, verbose_name='Expense amount')),
                ('payment_method', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense_transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='transacation date')),
                ('amount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(max_length=200)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expense')),
            ],
        ),
    ]
