# Generated by Django 4.1 on 2022-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('M-Pesa', 'M-pesa'), ('Credit Card', 'Credit Card')], max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Expense Title'),
        ),
    ]
