# Generated by Django 4.1 on 2022-10-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_payment_option_expense_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Date',
            field=models.DateField(default='2022-10-04', verbose_name='Date incurred'),
        ),
    ]
