# Generated by Django 4.1 on 2022-10-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('M-Pesa', 'M-pesa'), ('Credit Card', 'Credit Card')], default='Cash', max_length=200),
        ),
    ]
