# Generated by Django 4.1 on 2022-10-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='ID',
            new_name='expense_id',
        ),
    ]
