# Generated by Django 4.1 on 2022-10-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_rename_id_expense_expense_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Date',
            field=models.DateField(default='2022-10-08', verbose_name='Date incurred'),
        ),
    ]
