# Generated by Django 4.1 on 2022-10-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='Item',
            field=models.CharField(choices=[['Laptops', 'Laptops']], max_length=200),
        ),
    ]
