# Generated by Django 4.1 on 2022-10-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='Amount',
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.CharField(choices=[['Jacob Watua', 'Jacob Watua'], ['sJadcob Watua Wanyonddsyisjdd', 'sJadcob Watua Wanyonddsyisjdd'], ['Bill Amos Khaemba', 'Bill Amos Khaemba'], ['Bill Amos Khaembaj', 'Bill Amos Khaembaj'], ['Bill Amos Khaembajd', 'Bill Amos Khaembajd'], ['Jemimah Rechael', 'Jemimah Rechael'], ['Jacob Watua Benjamin', 'Jacob Watua Benjamin'], ['Jacobo Watua', 'Jacobo Watua'], ['Jacocbo Watua', 'Jacocbo Watua'], ['Jacdocbo Watua', 'Jacdocbo Watua'], ['Jacdfocbo Watua', 'Jacdfocbo Watua'], ['Jacdfojcbo Watua', 'Jacdfojcbo Watua'], ['Jacdfojchbo Watua', 'Jacdfojchbo Watua'], ['Jacddfojchbo Watua', 'Jacddfojchbo Watua'], ['Jacddfojchbo jWatua', 'Jacddfojchbo jWatua'], ['Jacddfojchbo jWatuaj', 'Jacddfojchbo jWatuaj'], ['Jacob Watuah', 'Jacob Watuah'], ['Jacob Watuajh', 'Jacob Watuajh'], ['Jacob Wnatuajh', 'Jacob Wnatuajh'], ['Jacob Wnatuajhj', 'Jacob Wnatuajhj'], ['Jacob Wnatbuajhj', 'Jacob Wnatbuajhj'], ['Jacob Wnatbuajhjd', 'Jacob Wnatbuajhjd'], ['Jacob Watuaj', 'Jacob Watuaj'], ['Jacob Watuadd', 'Jacob Watuadd'], ['Jacob Watuaddg', 'Jacob Watuaddg'], ['Jemimah Rechaeld', 'Jemimah Rechaeld'], ['Jemimah Rechaeldd', 'Jemimah Rechaeldd'], ['Jacob Watuae', 'Jacob Watuae'], ['sJacob Watua', 'sJacob Watua'], ['Jacob Watklua', 'Jacob Watklua'], ['Jacob WatuaDF', 'Jacob WatuaDF'], ['Jacob Watuasf', 'Jacob Watuasf'], ['sdJacob Watua', 'sdJacob Watua'], ['Jacob Watuafgdfg', 'Jacob Watuafgdfg'], ['Jacob Waddtua', 'Jacob Waddtua'], ['Jacob Watuasad', 'Jacob Watuasad'], ['Jacob Watuasa', 'Jacob Watuasa'], ['Jacob Watuadsf', 'Jacob Watuadsf'], ['Jacob Watuaad', 'Jacob Watuaad'], ['Timothy Gacia Tulus', 'Timothy Gacia Tulus'], ['Timothy Gacia Tulusds', 'Timothy Gacia Tulusds'], ['Isaac', 'Isaac'], ['Jacob Watuaikgjkgjkgyuj', 'Jacob Watuaikgjkgjkgyuj'], ['Jacob Benjamin', 'Jacob Benjamin']], max_length=250),
        ),
    ]
