# Generated by Django 4.1 on 2022-09-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=200)),
                ('Email_Address', models.EmailField(max_length=254, verbose_name='Enter email')),
                ('Phone', models.IntegerField()),
                ('Priority', models.CharField(max_length=200)),
            ],
        ),
    ]
