# Generated by Django 4.1 on 2022-09-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Priority',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Moderate'), ('3', 'Low')], max_length=200),
        ),
    ]
