# Generated by Django 4.1 on 2022-09-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
