# Generated by Django 4.1 on 2022-09-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('Vendor_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=200)),
                ('Email_Address', models.EmailField(max_length=254, verbose_name="vendor's email")),
                ('Phone', models.IntegerField(verbose_name="Vendor's phone number")),
                ('Priority', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='vendor_transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='transacation date')),
                ('amount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(max_length=200)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
