# Generated by Django 4.1 on 2022-09-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vendor_transaction',
        ),
    ]
