# Generated by Django 4.1 on 2022-10-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_delete_vendor_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Priority',
            field=models.CharField(choices=[['High', 'High'], ['Moderate', 'Moderate'], ['Low', 'Low']], max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Vendor_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
