# Generated by Django 4.1 on 2022-09-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='User Email', max_length=254)),
                ('phone', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
