# Generated by Django 4.1 on 2022-09-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('Purchase_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Item', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
                ('Amount', models.IntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='transacation date')),
                ('amount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(max_length=200)),
                ('Purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase')),
            ],
        ),
    ]
