# Generated by Django 4.1 on 2022-09-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Amount',
        ),
        migrations.AddField(
            model_name='purchase',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('M-Pesa', 'M-pesa'), ('Credit Card', 'Credit Card')], default='Cash', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Purchase_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='purchase_transaction',
        ),
    ]
