# Generated by Django 4.1 on 2022-09-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_purchase_amount_purchase_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Date',
        ),
    ]
