# Generated by Django 4.1 on 2022-09-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='date',
        ),
    ]
