# Generated by Django 4.1 on 2022-09-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_remove_purchase_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
