# Generated by Django 4.1 on 2022-09-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0002_delete_vendor_transaction'),
        ('purchases', '0008_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('Purchase_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Item', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('M-Pesa', 'M-pesa'), ('Credit Card', 'Credit Card')], default='Cash', max_length=200)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
