# Generated by Django 4.1 on 2022-09-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='Date',
            field=models.DateField(blank=True, help_text='Date Purchased', null=True),
        ),
    ]
