# Generated by Django 4.1 on 2022-09-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_alter_purchase_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.CharField(choices=[['Jacob Watua', 'Jacob Watua']], max_length=200),
        ),
    ]
