# Generated by Django 4.1 on 2022-09-28 05:33

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_alter_purchase_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=datetime.now().strftime("%Y-%m-%d")),
        ),
    ]
