# Generated by Django 4.1 on 2022-09-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_alter_purchase_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseTransaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Item', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField(default=0)),
                ('purchase_date', models.DateField(default='2022-09-29')),
                ('Price', models.IntegerField(default=0)),
                ('payment_method', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_date',
        ),
    ]
